---
- name: stop cloudcore
  fail: msg="don't install registry on the nodes"
  when: (registry_ip_address) in (groups['nodes']) or (registry_ip_address) in (groups['edges']) 
- name: stop cloudcore
  fail: msg="please config more then 2 masters"
  when: groups.masters|length == 2

